# Configuration file for AC Coulomb Blockade Oscilations SET.
# Copyright (C) 2019  Carlos Kometter

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

file:
  data_dir: CBO
  file_name: AC-2T
  comment:  AC CBO at 2T with LPF between SET and lockin input and auto phase.

lockin: SR830  # Write 'SR830' or '7820'

lockin_settings:
  tc: 0.3
  sensitiviy: 1.0
  amplitude: 0.004
  freq: 189.82
  phase: AUTO



dacadc_settings:
  delay_unit: 1 # 0 for microseconds and 1 for miliseconds
  timeout: 20  # Seconds
  dac1_ch: 0   # gate
  dac2_ch: 1   # set
  dac1_offset: 0.0 # Not in use
  dac2_offset: 0.0 # Not in use
  adc1_ch: 0
  adc2_ch: 1

measurement: CBO

CBO:
  v1: vset [V]
  v2: vgate [V]


# !!!!!!!! SET IS VGATE !!!!!!!
meas_parameters:
  vset_pnts: 1000
  vgate_pnts: 200
  vset_rng:
    - 0.0
    - 10.0
  vgate_rng:
    - -10.0
    - 10.0
  delay: 15000
