# Configuration file for AC Coulomb Blockade Oscilations SET.
# Copyright (C) 2019  Carlos Kometter

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

file:
  data_dir: CBO
  file_name: AC-2T
  comment: CBO at 2T.

lockin: SR830  # Write 'SR830' or '7820'

lockin_settings:
  tc: 0.001
  sensitiviy: 200.0e-3

dacadc_settings:
  dac1_ch: 0
  dac2_ch: 1
  dac1_offset: 0.0
  dac2_offset: 0.0
  adc1_ch: 0
  adc2_ch: 1

measurement: CBO

CBO:
  v1: vset [V]
  v2: vgate [V]

meas_parameters:
  vset_pnts: 33
  vgate_pnts: 10
  vset_rng:
    - -10.0
    - 10.0
  vgate_rng:
    - 0.0
    - 10.0