# Configuration file for AC Coulomb Blockade Oscilations SET.
# Copyright (C) 2019  Carlos Kometter

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

file:
  data_dir: CBO
  file_name: Debugging
  comment: Comment

#lockin: SR830  # Write 'SR830' or '7820'

lockin_settings:
  tc: 0.03
  sensitivity: 0.1
  attenuation: 40
  amplitude: 0.004
  freq: 371.6
  phase: 87.28

dacadc_settings:
  delay_unit: 1 # 0 for microseconds and 1 for miliseconds
  timeout: 20  # Seconds
  dac1_ch: 0   # Vgate fast
  dac2_ch: 1   # Vset slow
  dac1_offset: 0.0 # Not in use
  dac2_offset: 0.0 # Not in use
  adc1_ch: 0
  adc2_ch: 1

measurement: CBO

CBO:
  v1: vgate [V]
  v2: vset [V]

meas_parameters:
  vgate_pnts: 2000 #200
  vset_pnts: 120 #550
  vgate_rng:
    - -10 #-7.0
    - 10 #7.0
  vset_rng:
    - -8.0    #-10.0
    - 8.0    #10.0
  delay: 90  # Check delay unit

# BE CAREFULL!!!
max_values:
  vgate_rate: 1 # V/s
  vgate_step_size: 10.0e-3 # V

  vset_rate: 1 # V/s
  vset_step_size: 10.0e-3 # V