# Configuration file for AC Coulomb Blockade Oscilations SET.
# Copyright (C) 2019  Carlos Kometter

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

file:
  data_dir: CBO
  file_name: AC-DC-2T
  comment: Bias tee 220 ohm and 100 micro farad which lowers the ac sineout by 7.26/10.

#lockin: SR830  # Write 'SR830' or '7820'

lockin_settings:
  tc: 0.1
  tc_db: 24
  sensitivity: 0.1
  attenuation: 0
  amplitude: 0.01
  freq: 500.0
  phase: 142.31

dacadc_settings:
  delay_unit: 1 # 0 for microseconds and 1 for miliseconds
  timeout: 30  # Seconds
  dac1_ch: 0   # Vgate fast
  dac2_ch: 1   # Vset slow
  dac1_offset: 0.0 # Not in use
  dac2_offset: 0.0 # Not in use
  adc1_ch: 0
  adc2_ch: 1

measurement: CBO

CBO:
  v1: vgate [V]
  v2: vset [V]

meas_parameters:
  vgate_pnts: 1200 #200
  vset_pnts: 80 #550
  vgate_rng:
    - -2.0 #-7.0
    - 10.0 #7.0
  vset_rng:
    - -7.0    #-10.0
    - 7.0    #10.0
  delay: 300  # Check delay unit

# BE CAREFULL!!!
max_values:
  vgate_rate: 1 # V/s
  vgate_step_size: 10.0e-3 # V

  vset_rate: 1 # V/s
  vset_step_size: 10.0e-3 # V